pipeline {
    agent any
    //test 123

    stages {
        stage('Trigger downstream') {
            steps {
                build job: 'matter-github-mirror-artifactory', parameters:[string(name: 'branchName', value: env.BRANCH_NAME), string(name:'buildNumber', value: env.BUILD_NUMBER)]
            }
        }
    }
}
