pipeline {
    agent any

    stages {
        stage('Trigger downstream') {
            steps {
                build job: 'sqa_test_branch', parameters:[
                string(name: 'branchName', value: env.BRANCH_NAME),
                string(name:'buildNumber', value: env.BUILD_NUMBER),
                string(name: 'repoUrl', value: 'https://stash.silabs.com/scm/wmn_tools/matter_github_jenkins.git')
                ]
            }
        }
    }
}