name: Build Silabs Examples apps

on:
    push:
# TODO add these lines back       branches:
#            - main
#            - "release_*"
    pull_request:
        branches:
            - main
            - "release_*"
    workflow_dispatch:

concurrency:
    group: silabs-build-examples-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-lighting-app:
        name: Build Lighting-App variations
        uses: ./.github/workflows/silabs-common-build.yaml
        with:
            example-app: "lighting-app"
            path-to-example-app: "slc/sample-app/lighting-app/efr32"
            output-directory: "./out/lighting-app"

    build-air-quality-sensor-app:
        name: Build Air-Quality-Sensor-App variations
        uses: ./.github/workflows/silabs-common-build.yaml
        with:
            example-app: "air-quality-sensor-app"
            path-to-example-app: "slc/sample-app/air-quality-sensor-app/efr32"            
            output-directory: "./out/air-quality-sensor-app"

    build-dishwasher-app:
        name: Build Dishwasher-App variations
        uses: ./.github/workflows/silabs-common-build.yaml
        with:
            example-app: "dishwasher-app"
            path-to-example-app: "slc/sample-app/dishwasher-app/efr32"
            output-directory: "./out/dishwasher-app"

    build-light-switch-app:
        name: Build Light-Switch-App variations
        uses: ./.github/workflows/silabs-common-build.yaml
        with:
            example-app: "light-switch-app"
            path-to-example-app: "slc/sample-app/light-switch-app/efr32"
            output-directory: "./out/light-switch-app"

    build-lock-app:
        name: Build Lock-App variations
        uses: ./.github/workflows/silabs-common-build.yaml
        with:
            example-app: "lock-app"
            path-to-example-app: "slc/sample-app/lock-app/efr32"
            output-directory: "./out/lock-app"

    build-thermostat:
        name: Build Thermostat variations
        uses: ./.github/workflows/silabs-common-build.yaml
        with:
            example-app: "thermostat"
            path-to-example-app: "slc/sample-app/thermostat/efr32"
            output-directory: "./out/thermostat" 

    build-window-app:
        name: Build Window-App variations
        uses: ./.github/workflows/silabs-common-build.yaml
        with:
            example-app: "window-app"
            path-to-example-app: "slc/sample-app/window-app/efr32"
            output-directory: "./out/window-app"

    build-fan-control-app:
        name: Build Fan-Control-App variations
        uses: ./.github/workflows/silabs-common-build.yaml
        with:
            example-app: "fan-control-app"
            path-to-example-app: "slc/sample-app/fan-control-app/efr32"
            output-directory: "./out/fan-control-app"

    build-multi-sensor-app:
        name: Build Multi-Sensor-App variations
        uses: ./.github/workflows/silabs-common-build.yaml
        with:
            example-app: "multi-sensor-app"
            path-to-example-app: "slc/sample-app/sensor-app/efr32"
            output-directory: "./out/multi-sensor-app"

    build-onoff-plug-app:
        name: Build OnOff-Plug-App variations
        uses: ./.github/workflows/silabs-common-build.yaml
        with:
            example-app: "onoff-plug-app"
            path-to-example-app: "slc/sample-app/onoff-plug-app/efr32"
            output-directory: "./out/onoff-plug-app"