name: Build Silabs Examples apps

on:
    push:
# TODO add these lines back       branches:
#            - main
#            - "release_*"
    pull_request:
        branches:
            - main
            - "release_*"
    workflow_dispatch:

concurrency:
    group: silabs-build-examples-${{ github.ref }}
    cancel-in-progress: true

jobs:
#    build-lighting-app:
#        name: Build Lighting-App variations
#        uses: ./.github/workflows/silabs-common-build.yaml
#        with:
#            example-app: "lighting-app"
#            output-directory: "./out/lighting-app"
#            build-type: "standard"
#
#    build-air-quality-sensor-app:
#        name: Build Air-Quality-Sensor-App variations
#        uses: ./.github/workflows/silabs-common-build.yaml
#        with:
#            example-app: "air-quality-sensor-app"
#            output-directory: "./out/air-quality-sensor-app"
#            build-type: "standard"
#
#
#    build-dishwasher-app:
#        name: Build Dishwasher-App variations
#        uses: ./.github/workflows/silabs-common-build.yaml
#        with:
#            example-app: "dishwasher-app"
#            output-directory: "./out/dishwasher-app"
#            build-type: "standard"
#
#
#    build-light-switch-app:
#        name: Build Light-Switch-App variations
#        uses: ./.github/workflows/silabs-common-build.yaml
#        with:
#            example-app: "light-switch-app"
#            output-directory: "./out/light-switch-app"
#            build-type: "standard"
#
#
#    build-lock-app:
#        name: Build Lock-App variations
#        uses: ./.github/workflows/silabs-common-build.yaml
#        with:
#            example-app: "lock-app"
#            output-directory: "./out/lock-app"
#            build-type: "standard"
#
#
#    build-thermostat:
#        name: Build Thermostat variations
#        uses: ./.github/workflows/silabs-common-build.yaml
#        with:
#            example-app: "thermostat"
#            output-directory: "./out/thermostat"
#            build-type: "standard"
#
#
#    build-window-app:
#        name: Build Window-App variations
#        uses: ./.github/workflows/silabs-common-build.yaml
#        with:
#            example-app: "window-app"
#            output-directory: "./out/window-app"
#            build-type: "standard"
#
#
#    build-fan-control-app:
#        name: Build Fan-Control-App variations
#        uses: ./.github/workflows/silabs-common-build.yaml
#        with:
#            example-app: "fan-control-app"
#            output-directory: "./out/fan-control-app"
#            build-type: "standard"


    build-multi-sensor-app:
        name: Build Multi-Sensor-App variations
        uses: ./.github/workflows/silabs-common-build.yaml
        with:
            example-app: "sensor-app"
            output-directory: "./out/sensor-app"
            build-type: "standard"


#    build-onoff-plug-app:
#        name: Build OnOff-Plug-App variations
#        uses: ./.github/workflows/silabs-common-build.yaml
#        with:
#            example-app: "onoff-plug-app"
#            output-directory: "./out/onoff-plug-app"
#            build-type: "standard"

    # THE LOGIC BELOW IS TO WAIT FOR JENKINS SANITY TEST TO FINISH, WHEN IT FINISHED IT WILL UPDATE THE check-runs.
    # HERE WE LIST THEM AND THEN EXTRACT THE CORRECT CHECK RUN ID. ONCE THAT IS DONE WE POLL THE TITLE, SUMMARY AND TEXT
    # OF THE CHECK RUN UNTIL THEY ARE NOT EMPTY. ONCE THEY ARE NOT EMPTY WE BREAK THE LOOP.
    wait-for-jenkins-status:
        name: Wait for Jenkins Status
        needs: build-multi-sensor-app
        runs-on: ubuntu-latest
        steps:
            - name: List Check Runs
              id: list_check_runs
              run: |
                  curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                       -H "Accept: application/vnd.github.v3+json" \
                        https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/check-runs > check_runs.json
                  cat check_runs.json

            - name: Extract Check Run ID
              id: extract_check_run_id
              run: |
                  CHECK_RUN_ID=$(jq -r --arg JOB_NAME "Wait for Jenkins Status" '.check_runs[] | select(.name == $JOB_NAME) | .id' check_runs.json)
                  echo "CHECK_RUN_ID=$CHECK_RUN_ID" >> $GITHUB_ENV

            - name: Wait for Check Run Output Update
              run: |
                  echo "Waiting for check run output to be updated..."
                  while true; do
                      response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          https://api.github.com/repos/${{ github.repository }}/check-runs/${CHECK_RUN_ID})

                      title=$(echo "$response" | jq -r '.output.title // empty')
                      summary=$(echo "$response" | jq -r '.output.summary // empty')
                      text=$(echo "$response" | jq -r '.output.text // empty')

                      if [[ -n "$title" && -n "$summary" && -n "$text" ]]; then
                          echo "Check run output updated:"
                          echo "Title: $title"
                          echo "Summary: $summary"
                          echo "Text: $text"
                          break
                      else
                          echo "Waiting for output fields to be updated..."
                          sleep 120
                      fi
                  done