name: Common Build

on:
    workflow_call:
        inputs:
            example-app:
                required: true
                type: string
            output-directory:
                required: true
                type: string
            build-type:
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/project-chip/chip-build-efr32:115

        strategy:
            fail-fast: false
            matrix:
                platform: [mg24]

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                submodules: 'true'

                

            - name: Create SLCW string configurations
              run: |
                echo "ADDITIONAL_APP_ARGS=thread" >> $GITHUB_ENV
                if [ ${{ ((matrix.platform  == '917-soc') || ( matrix.platform  == '917-ncp' && ( inputs.example-app  == 'lock-app' ||  inputs.example-app  == 'thermostat' ||  inputs.example-app  == 'window-app')) || ( matrix.platform  == 'wf200' && ( inputs.example-app  == 'lock-app' ||  inputs.example-app  == 'thermostat' )) || ( matrix.platform  == 'rs911x' && ( inputs.example-app  == 'lock-app' ||  inputs.example-app  == 'thermostat' ))) }} = true ]; then
                  echo "ADDITIONAL_APP_ARGS=${{ matrix.platform }}" >> $GITHUB_ENV
                fi

                echo "BOOTLOADER=" >> $GITHUB_ENV
                if [ ${{ matrix.platform == '917-soc' }} != true ] ; then
                  echo "BOOTLOADER=-bootloader" >> $GITHUB_ENV
                fi

                echo "PLATFORM=efr32" >> $GITHUB_ENV
                if [ ${{ matrix.platform == '917-soc' }} = true ] ; then
                  echo "PLATFORM=siwx917" >> $GITHUB_ENV
                fi    

                echo "SERIES=series-2" >> $GITHUB_ENV
                if [ ${{ matrix.platform == '917-soc' }} = true ] ; then
                  echo "SERIES=siwx917" >> $GITHUB_ENV
                fi

                echo "JSON_FILE_PATH=${{ matrix.platform == 'mg24' && './.github/silabs-builds-mg24.json' ||
                         matrix.platform == '917-ncp' && './.github/silabs-builds-mg24.json' ||
                         matrix.platform == 'wf200' && './.github/silabs-builds-mg24.json' ||
                         matrix.platform == 'rs911x' && './.github/silabs-builds-mg24.json' ||
                         matrix.platform == 'mgm24' && './.github/silabs-builds-mgm24.json' ||
                         matrix.platform == 'mg26' && './.github/silabs-builds-mg26.json' ||
                         matrix.platform == '917-soc' && './.github/silabs-builds-siwx.json' }}" >> $GITHUB_ENV


            - name: Create artifact paths to be uploaded
              shell: bash
              run: |
                echo "boards=$(jq -c '.standard.default[0].boards' ${{env.JSON_FILE_PATH}})"
                artifacts=""
                jq --raw-output '.standard.default[0].boards[]' ${{env.JSON_FILE_PATH}} | while read board; do
                  echo "Processing board: $board"
                  if [ ${{ matrix.platform == '917-soc' }} = true ] ; then
                    board=$(echo "$board" | sed "s/'//g; s/;wiseconnect3_sdk//")
                    artifacts="${artifacts}out/${board}/${{ inputs.example-app }}-${{ env.ADDITIONAL_APP_ARGS }}-solution/${{ inputs.example-app }}-${{ env.ADDITIONAL_APP_ARGS }}/build/debug/${{ inputs.example-app }}-${{ env.ADDITIONAL_APP_ARGS }}.s37 "
                  else
                    artifacts="${artifacts}out/${board}/${{ inputs.example-app }}-${{ env.ADDITIONAL_APP_ARGS }}-solution/artifact/${{ inputs.example-app }}-${{ env.ADDITIONAL_APP_ARGS }}${{ env.BOOTLOADER }}-full.s37 "
                  fi
                done
                echo "Final artifacts: '$artifacts'"
                echo "Final artifacts: {$artifacts}"
                echo "ARTIFACTS=${artifacts}" >> $GITHUB_ENV

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: ${{ inputs.example-app }}-${{ env.ADDITIONAL_APP_ARGS }}${{ env.BOOTLOADER }}-full.s37 ${{ matrix.platform }}
                path: ${{ env.ARTIFACTS }}

