name: Common Build

on:
    workflow_call:
        inputs:
            example-app:
                required: true
                type: string
            output-directory:
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
          boards: ${{ steps.extract_boards.outputs.boards }}
        container:
            image: ghcr.io/project-chip/chip-build-efr32:115

        strategy:
            fail-fast: false
            matrix:
                platform: [mg24]

        steps:
            - name: Checkout
              uses: actions/checkout@v4




            - name: Create SLCP string configurations
              run: |
                echo "ADDITIONAL_APP_ARGS=thread" >> $GITHUB_ENV
                if [ ${{ ((matrix.platform  == '917-soc') || ( matrix.platform  == '917-ncp' && ( inputs.example-app  == 'lock-app' ||  inputs.example-app  == 'thermostat' ||  inputs.example-app  == 'window-app')) || ( matrix.platform  == 'wf200' && ( inputs.example-app  == 'lock-app' ||  inputs.example-app  == 'thermostat' )) || ( matrix.platform  == 'rs911x' && ( inputs.example-app  == 'lock-app' ||  inputs.example-app  == 'thermostat' ))) }} = true ]; then
                  echo "ADDITIONAL_APP_ARGS=${{ matrix.platform }}" >> $GITHUB_ENV
                fi

                echo "BOOTLOADER=" >> $GITHUB_ENV
                if [ ${{ matrix.platform == '917-soc' }} != true ] ; then
                  echo "BOOTLOADER=-bootloader" >> $GITHUB_ENV
                fi

                echo "JSON_FILE_PATH=${{ matrix.platform == 'mg24' && './.github/silabs-builds-mg24.json' ||
                                         matrix.platform == '917-ncp' && './.github/silabs-builds-mg24.json' ||
                                         matrix.platform == 'wf200' && './.github/silabs-builds-mg24.json' ||
                                         matrix.platform == 'rs911x' && './.github/silabs-builds-mg24.json' ||
                                         matrix.platform == 'mgm24' && './.github/silabs-builds-mgm24.json' ||
                                         matrix.platform == 'mg26' && './.github/silabs-builds-mg26.json' ||
                                         matrix.platform == '917-soc' && './.github/silabs-builds-siwx.json' }}" >> $GITHUB_ENV

                echo "PLATFORM=efr32" >> $GITHUB_ENV
                if [ ${{ matrix.platform == '917-soc' }} = true ] ; then
                  echo "PLATFORM=siwx917" >> $GITHUB_ENV
                fi    

                echo "SERIES=series-2" >> $GITHUB_ENV
                if [ ${{ matrix.platform == '917-soc' }} = true ] ; then
                  echo "SERIES=siwx917" >> $GITHUB_ENV
                fi  

            - name: Extract board list from json
              id: extract_boards
              run: echo "boards=$(jq -c '.default[0].boards' ${{env.JSON_FILE_PATH}})" 

    upload:
        runs-on: ubuntu-latest
        needs: build
        strategy:
            matrix:
                board: ${{ fromJson(needs.build.outputs.boards) }}
        steps:

          - name: Board ID
            run: |
              echo "Processing board: ${{ matrix.board }}"

          - uses: actions/upload-artifact@v4
            with:
              name: ${{ inputs.example-app }}-${{ env.ADDITIONAL_APP_ARGS }} ${{ matrix.board }}
              path: ${{ github.workspace }}/out/${{matrix.board}}/${{ inputs.example-app }}-${{ env.ADDITIONAL_APP_ARGS }}-solution/artifact/${{ inputs.example-app }}-${{ env.ADDITIONAL_APP_ARGS }}${{ env.BOOTLOADER }}-full.s37
                