name: SQA Build

on:
  push: # To be removed once testing is finished
  workflow_dispatch:
  workflow_run:
    workflows: ["Full Build"]
    types:
      - completed

jobs:
  ota_thread_v2:
    # Job triggered either automatically by release_ or main branch, or manual trigger (if needed)
    # if: ${{ github.event_name == 'workflow_run' && (startsWith(github.event.workflow_run.head_branch, 'release_' || github.event.workflow_run.head_branch == 'main')) || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        # Every app builds for every board and suffix
        app: [light-switch-app, lighting-app, lock-app]
        # TODO: Will need to add Rainier once available
        board: [brd4116a, brd4186c, brd4187c, brd4316a, brd4337a, brd4351a]
        suffix: [ thread ]
        app_type: [ ota-v2 ]
        family: [series-2]
        addAppComponent: [ "" ]
        configs: [ 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"' ]
        include:
#          - board: brd1019a
#            app: lighting-app
#            family: series-3
#            suffix: thread
#            app_type: ota-v2
#            addAppComponent: ""
#            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"'
#          - board: brd1019a
#            app: zigbee-matter
#            family: series-3
#            suffix: light
#            app_type: ota-v2
#            addAppComponent: matter_zigbee_concurrent;matter
#            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"'
#          - board: brd1019a
#            app: zigbee-matter
#            family: series-3
#            suffix: light
#            app_type: ota-v2
#            addAppComponent: matter_zigbee_sequential;matter
#            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"'
          - board: brd4116a
            app: zigbee-matter
            family: series-2
            suffix: light
            app_type: ota-v2
            addAppComponent: matter_zigbee_concurrent;matter
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"'
          - board: brd4116a
            app: zigbee-matter
            family: series-2
            suffix: light
            app_type: ota-v2
            addAppComponent: matter_zigbee_sequential;matter
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"'
          - board: brd4187c
            app: zigbee-matter
            family: series-2
            suffix: light
            app_type: ota-v2
            addAppComponent: matter_zigbee_concurrent;matter
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"'
          - board: brd4187c
            app: zigbee-matter
            family: series-2
            suffix: light
            app_type: ota-v2
            addAppComponent: matter_zigbee_sequential;matter
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"'

    name: ${{ matrix.app }}-${{ matrix.suffix }} ${{ matrix.addAppComponent}} ${{ matrix.board }} ${{ matrix.app_type }}

    uses: ./.github/workflows/generate-and-build.yaml
    with:
      app: ${{ matrix.app }}
      board: ${{ matrix.board }}
      suffix: ${{ matrix.suffix }}
      addAppComponent: ${{ matrix.addAppComponent }}
      family: ${{ matrix.family }}
      configs: ${{ matrix.configs }}
      workflow_name: 'SQA Build'

  ota_thread_v3:
    # Job triggered either automatically by release_ or main branch, or manual trigger (if needed)
    # if: ${{ github.event_name == 'workflow_run' && (startsWith(github.event.workflow_run.head_branch, 'release_' || github.event.workflow_run.head_branch == 'main')) || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        # Every app builds for every board and suffix
        app: [ lighting-app, lock-app ]
        board: [ brd4116a, brd4187c, brd4316a, brd4337a ]
        suffix: [ thread ]
        app_type: [ ota-v3 ]
        addAppComponent: [ "" ]
        configs: [ 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:3,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"3\"' ]
        include:
          - board: brd4116a
            app: zigbee-matter
            suffix: light
            app_type: ota-v3
            addAppComponent: matter_zigbee_concurrent;matter
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:3,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"3\"'
          - board: brd4116a
            app: zigbee-matter
            suffix: light
            app_type: ota-v3
            addAppComponent: matter_zigbee_sequential;matter
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:3,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"3\"'
          - board: brd4187c
            app: zigbee-matter
            suffix: light
            app_type: ota-v3
            addAppComponent: matter_zigbee_concurrent;matter
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:3,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"3\"'
          - board: brd4187c
            app: zigbee-matter
            suffix: light
            app_type: ota-v3
            addAppComponent: matter_zigbee_sequential;matter
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:3,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"3\"'

    name: ${{ matrix.app }}-${{ matrix.suffix }} ${{ matrix.addAppComponent}} ${{ matrix.board }} ${{ matrix.app_type }}

    uses: ./.github/workflows/generate-and-build.yaml
    with:
      app: ${{ matrix.app }}
      board: ${{ matrix.board }}
      suffix: ${{ matrix.suffix }}
      addAppComponent: ${{ matrix.addAppComponent }}
      family: series-2
      configs: ${{ matrix.configs }}
      workflow_name: 'SQA Build'

  ota_thread_lz4_v2:
    # Job triggered either automatically by release_ or main branch, or manual trigger (if needed)
    # if: ${{ github.event_name == 'workflow_run' && (startsWith(github.event.workflow_run.head_branch, 'release_' || github.event.workflow_run.head_branch == 'main')) || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        # Every app builds for every board and suffix
        app: [ lighting-app, lock-app ]
        board: [ brd4116a, brd4187c, brd4316a, brd4337a ]
        suffix: [ thread ]
        app_type: [ ota-lz4-v2 ]
        addAppComponent: [ "" ]
        addBlComponent: [ "bootloader_gbl_compression_lz4" ]
        configs: [ 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"' ]
        include:
          - board: brd4116a
            app: zigbee-matter
            suffix: light
            app_type: ota-lz4-v2
            addAppComponent: matter_zigbee_concurrent;matter
            addBlComponent: "bootloader_gbl_compression_lz4"
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"'
          - board: brd4116a
            app: zigbee-matter
            suffix: light
            app_type: ota-lz4-v2
            addAppComponent: matter_zigbee_sequential;matter
            addBlComponent: "bootloader_gbl_compression_lz4"
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"'
          - board: brd4187c
            app: zigbee-matter
            suffix: light
            app_type: ota-lz4-v2
            addAppComponent: matter_zigbee_concurrent;matter
            addBlComponent: "bootloader_gbl_compression_lz4"
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"'
          - board: brd4187c
            app: zigbee-matter
            suffix: light
            app_type: ota-lz4-v2
            addAppComponent: matter_zigbee_sequential;matter
            addBlComponent: "bootloader_gbl_compression_lz4"
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"'

    name: ${{ matrix.app }}-${{ matrix.suffix }} ${{ matrix.addAppComponent}} ${{ matrix.board }} ${{ matrix.app_type }}

    uses: ./.github/workflows/generate-and-build.yaml
    with:
      app: ${{ matrix.app }}
      board: ${{ matrix.board }}
      suffix: ${{ matrix.suffix }}
      addAppComponent: ${{ matrix.addAppComponent }}
      addBlComponent: ${{ matrix.addBlComponent }}
      family: series-2
      configs: ${{ matrix.configs }}
      workflow_name: 'SQA Build'

  ota_thread_lz4_v3:
    # Job triggered either automatically by release_ or main branch, or manual trigger (if needed)
    # if: ${{ github.event_name == 'workflow_run' && (startsWith(github.event.workflow_run.head_branch, 'release_' || github.event.workflow_run.head_branch == 'main')) || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        # Every app builds for every board and suffix
        app: [ lighting-app, lock-app ]
        board: [ brd4116a, brd4187c, brd4316a, brd4337a ]
        suffix: [ thread ]
        app_type: [ ota-lz4-v3 ]
        addAppComponent: [ "" ]
        addBlComponent: [ "bootloader_gbl_compression_lz4" ]
        configs: [ 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:3,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"3\"' ]
        include:
          - board: brd4116a
            app: zigbee-matter
            suffix: light
            app_type: ota-lz4-v3
            addAppComponent: matter_zigbee_concurrent;matter
            addBlComponent: "bootloader_gbl_compression_lz4"
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:3,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"3\"'
          - board: brd4116a
            app: zigbee-matter
            suffix: light
            app_type: ota-lz4-v3
            addAppComponent: matter_zigbee_sequential;matter
            addBlComponent: "bootloader_gbl_compression_lz4"
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:3,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"3\"'
          - board: brd4187c
            app: zigbee-matter
            suffix: light
            app_type: ota-lz4-v3
            addAppComponent: matter_zigbee_concurrent;matter
            addBlComponent: "bootloader_gbl_compression_lz4"
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:3,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"3\"'
          - board: brd4187c
            app: zigbee-matter
            suffix: light
            app_type: ota-lz4-v3
            addAppComponent: matter_zigbee_sequential;matter
            addBlComponent: "bootloader_gbl_compression_lz4"
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:3,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"3\"'

    name: ${{ matrix.app }}-${{ matrix.suffix }} ${{ matrix.addAppComponent}} ${{ matrix.board }} ${{ matrix.app_type }}

    uses: ./.github/workflows/generate-and-build.yaml
    with:
      app: ${{ matrix.app }}
      board: ${{ matrix.board }}
      suffix: ${{ matrix.suffix }}
      addAppComponent: ${{ matrix.addAppComponent }}
      addBlComponent: ${{ matrix.addBlComponent }}
      family: series-2
      configs: ${{ matrix.configs }}
      workflow_name: 'SQA Build'

  ota_wifi_v2:
    # Job triggered either automatically by release_ or main branch, or manual trigger (if needed)
    # if: ${{ github.event_name == 'workflow_run' && (startsWith(github.event.workflow_run.head_branch, 'release_' || github.event.workflow_run.head_branch == 'main')) || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        # Every app builds for every board and suffix
        app: [ lighting-app, lock-app ]
        board: [ brd4338a, brd4342a ]
        suffix: [ 917-soc ]
        app_type: [ ota-v2 ]
        family: [ siwx917 ]
        board_extension: [ ;wiseconnect3_sdk ]
        configs: [ 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"' ]
        include:
          - board: brd4187c
            app: lock-app
            app_type: ota-v2
            suffix: 917-ncp
            family: series-2
            board_extension: ""
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"'
          - board: brd4187c
            app: lock-app
            app_type: ota-v2
            suffix: wf200
            family: series-2
            board_extension: ""
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"'
          - board: brd4187c
            app: lock-app
            app_type: ota-v2
            suffix: rs911x
            family: series-2
            board_extension: ""
            configs: 'CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION:2,CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING:\"2\"'

    name: ${{ matrix.app }}-${{ matrix.suffix }} ${{ matrix.board }} ${{ matrix.app_type }}

    uses: ./.github/workflows/generate-and-build.yaml
    with:
      app: ${{ matrix.app }}
      board: ${{ matrix.board }}
      suffix: ${{ matrix.suffix }}
      family: ${{ matrix.family }}
      configs: ${{ matrix.configs }}
      board_extension: ${{ matrix.board_extension }}
      workflow_name: 'SQA Build'

  m_ota_thread:
    # Job triggered either automatically by release_ or main branch, or manual trigger (if needed)
    # if: ${{ github.event_name == 'workflow_run' && (startsWith(github.event.workflow_run.head_branch, 'release_' || github.event.workflow_run.head_branch == 'main')) || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        # Every app builds for every board and suffix
        app: [ lighting-app, lock-app, dishwasher-app, window-app ]
        board: [ brd4116a, brd4187c ]
        suffix: [ thread ]
        app_type: [ m-ota ]
        family: [ series-2 ]
        addAppComponent: [ 'matter_multi_image_ota;matter,matter_multi_image_custom_processor;matter' ]
        removeAppComponent: [ 'matter_ota_support;matter' ]

    name: ${{ matrix.app }}-${{ matrix.suffix }} ${{ matrix.addAppComponent}} ${{ matrix.removeAppComponent}} ${{ matrix.board }} ${{ matrix.app_type }}

    uses: ./.github/workflows/generate-and-build.yaml
    with:
      app: ${{ matrix.app }}
      board: ${{ matrix.board }}
      suffix: ${{ matrix.suffix }}
      addAppComponent: ${{ matrix.addAppComponent }}
      removeAppComponent: ${{ matrix.removeAppComponent }}
      family: ${{ matrix.family }}
      workflow_name: 'SQA Build'

  m_ota_enc_thread:
    # Job triggered either automatically by release_ or main branch, or manual trigger (if needed)
    # if: ${{ github.event_name == 'workflow_run' && (startsWith(github.event.workflow_run.head_branch, 'release_' || github.event.workflow_run.head_branch == 'main')) || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        # Every app builds for every board and suffix
        app: [ lighting-app, lock-app, dishwasher-app, window-app ]
        board: [ brd4116a, brd4187c ]
        suffix: [ thread ]
        app_type: [ m-ota-enc ]
        family: [ series-2 ]
        addAppComponent: [ 'matter_multi_image_ota;matter,matter_multi_image_ota_encryption;matter,matter_multi_image_custom_processor;matter' ]
        removeAppComponent: [ 'matter_ota_support;matter' ]

    name: ${{ matrix.app }}-${{ matrix.suffix }} ${{ matrix.addAppComponent}} ${{ matrix.removeAppComponent}} ${{ matrix.board }} ${{ matrix.app_type }}

    uses: ./.github/workflows/generate-and-build.yaml
    with:
      app: ${{ matrix.app }}
      board: ${{ matrix.board }}
      suffix: ${{ matrix.suffix }}
      addAppComponent: ${{ matrix.addAppComponent }}
      removeAppComponent: ${{ matrix.removeAppComponent }}
      family: ${{ matrix.family }}
      workflow_name: 'SQA Build'

  low_power:
    # Job triggered either automatically by release_ or main branch, or manual trigger (if needed)
    # if: ${{ github.event_name == 'workflow_run' && (startsWith(github.event.workflow_run.head_branch, 'release_' || github.event.workflow_run.head_branch == 'main')) || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        # Every app builds for every board and suffix
        app: [ lock-app, light-switch-app ]
        board: [ brd4186c, brd4338a ]
        suffix: [ thread ]
        app_type: [ low-power ]
        family: [ series-2 ]
        addAppComponent: [ ',matter_platform_low_power;matter' ]
        # TODO: do we add the idle time 60 to this?
        removeAppComponent: [ 'matter_shell;matter,matter_qr_code;matter,matter_lcd;matter,matter_lcd_917SOC;matter,matter_thread_cli;matter,matter_default_lcd_config;matter' ]
        include:
          - board: brd4338a
            suffix: 917-soc
            family: siwx917
            app: lock-app
            app_type: low-power
            board_extension: ;wiseconnect3_sdk
            addAppComponent: ',matter_platform_low_power;matter'
            removeAppComponent: 'matter_shell;matter,matter_qr_code;matter,matter_lcd;matter,matter_lcd_917SOC;matter,matter_thread_cli;matter,matter_default_lcd_config;matter'
          - board: brd4338a
            suffix: 917-soc
            family: siwx917
            app: light-switch-app
            app_type: low-power
            board_extension: ;wiseconnect3_sdk
            addAppComponent: ',matter_platform_low_power;matter'
            removeAppComponent: 'matter_shell;matter,matter_qr_code;matter,matter_lcd;matter,matter_lcd_917SOC;matter,matter_thread_cli;matter,matter_default_lcd_config;matter'

    name: ${{ matrix.app }}-${{ matrix.suffix }} ${{ matrix.addAppComponent}} ${{ matrix.removeAppComponent}} ${{ matrix.board }} ${{ matrix.app_type }}

    uses: ./.github/workflows/generate-and-build.yaml
    with:
      app: ${{ matrix.app }}
      board: ${{ matrix.board }}
      suffix: ${{ matrix.suffix }}
      addAppComponent: ${{ matrix.addAppComponent }}
      removeAppComponent: ${{ matrix.removeAppComponent }}
      family: ${{ matrix.family }}
      board_extension: ${{ matrix.board_extension }}
      workflow_name: 'SQA Build'

  lto:
    # Job triggered either automatically by release_ or main branch, or manual trigger (if needed)
    # if: ${{ github.event_name == 'workflow_run' && (startsWith(github.event.workflow_run.head_branch, 'release_' || github.event.workflow_run.head_branch == 'main')) || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        # Every app builds for every board and suffix
        app: [ lock-app, lighting-app ]
        board: [ brd4187c, brd4116a ]
        suffix: [ thread ]
        app_type: [ lto ]
        family: [ series-2 ]
        addAppComponent: [ ', toolchain_gcc_lto' ]

    name: ${{ matrix.app }}-${{ matrix.suffix }} ${{ matrix.addAppComponent}} ${{ matrix.board }} ${{ matrix.app_type }}

    uses: ./.github/workflows/generate-and-build.yaml
    with:
      app: ${{ matrix.app }}
      board: ${{ matrix.board }}
      suffix: ${{ matrix.suffix }}
      addAppComponent: ${{ matrix.addAppComponent }}
      removeAppComponent: ${{ matrix.removeAppComponent }}
      family: ${{ matrix.family }}
      workflow_name: 'SQA Build'

  icd_idm:
    # Job triggered either automatically by release_ or main branch, or manual trigger (if needed)
    # if: ${{ github.event_name == 'workflow_run' && (startsWith(github.event.workflow_run.head_branch, 'release_' || github.event.workflow_run.head_branch == 'main')) || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        # Every app builds for every board and suffix
        app: [ lock-app, light-switch-app, sensor-app ]
        board: [ brd4186c, brd4187c, brd4116a ]
        suffix: [ thread ]
        app_type: [ icd-idm60 ]
        family: [ series-2 ]
        configs: [ 'SL_IDLE_MODE_DURATION_S:60' ]
        include:
          - board: brd4186c
            app: lock-app
            suffix: thread
            app_type: icd-idm60
            family: series-2
            configs: 'SL_IDLE_MODE_DURATION_S:60'
          - board: brd4338a
            app: lock-app
            app_type: icd-idm60
            suffix: 917-soc
            family: siwx917
            board_extension: ;wiseconnect3_sdk
            configs: 'SL_IDLE_MODE_DURATION_S:60'
          - board: brd4338a
            app: light-switch-app
            app_type: icd-idm60
            suffix: 917-soc
            family: siwx917
            board_extension: ;wiseconnect3_sdk
            configs: 'SL_IDLE_MODE_DURATION_S:60'

    name: ${{ matrix.app }}-${{ matrix.suffix }} ${{ matrix.addAppComponent}} ${{ matrix.removeAppComponent}} ${{ matrix.board }} ${{ matrix.app_type }}

    uses: ./.github/workflows/generate-and-build.yaml
    with:
      app: ${{ matrix.app }}
      board: ${{ matrix.board }}
      suffix: ${{ matrix.suffix }}
      configs: ${{ matrix.configs }}
      family: ${{ matrix.family }}
      board_extension: ${{ matrix.board_extension }}
      workflow_name: 'SQA Build'

  icd_sync:
    # Job triggered either automatically by release_ or main branch, or manual trigger (if needed)
    # if: ${{ github.event_name == 'workflow_run' && (startsWith(github.event.workflow_run.head_branch, 'release_' || github.event.workflow_run.head_branch == 'main')) || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        # Every app builds for every board and suffix
        app: [ lock-app ]
        board: [ brd4186c, brd4187c, brd4116a ]
        suffix: [ thread ]
        app_type: [ icd-sync-false ]
        family: [ series-2 ]
        configs: [ 'SL_IDLE_MODE_DURATION_S:60,CHIP_CONFIG_SYNCHRONOUS_REPORTS_ENABLED:0' ]
        include:
          - board: brd4338a
            app: lock-app
            app_type: icd-sync-false
            suffix: 917-soc
            family: siwx917
            board_extension: ;wiseconnect3_sdk
            configs: 'SL_IDLE_MODE_DURATION_S:60,CHIP_CONFIG_SYNCHRONOUS_REPORTS_ENABLED:0'

    name: ${{ matrix.app }}-${{ matrix.suffix }} ${{ matrix.addAppComponent}} ${{ matrix.removeAppComponent}} ${{ matrix.board }} ${{ matrix.app_type }}

    uses: ./.github/workflows/generate-and-build.yaml
    with:
      app: ${{ matrix.app }}
      board: ${{ matrix.board }}
      suffix: ${{ matrix.suffix }}
      configs: ${{ matrix.configs }}
      family: ${{ matrix.family }}
      board_extension: ${{ matrix.board_extension }}
      workflow_name: 'SQA Build'